config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # User authentication routes with custom controller
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  # Admin authentication routes
  devise_for :admin_users, path: "admin_users"

  # Home page
  root "pages#home"

  # App Routes below
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post "add_item/:product_id", to: "carts#add_item", as: :add_item
    delete "remove_item/:product_id", to: "carts#remove_item", as: :remove_item
    get "checkout", to: "carts#checkout", as: :checkout
  end

  authenticate :user do
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        get :confirm
      end
      member do
        patch :cancel
      end
    end

    resources :payments, only: [:new, :create] do
      collection do
        get :success
        get :failure
      end
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || t('site.name')
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/manifest.json", :rel => "manifest"}/
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = javascript_importmap_tags
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    %link{href: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css", rel: "stylesheet", integrity: "sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH", crossorigin: "anonymous"}
    %link{href: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css", rel: "stylesheet"}
    %script{src: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js", integrity: "sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz", crossorigin: "anonymous"}

  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      .container
        = link_to t('site.name'), root_path, class: "navbar-brand"
        %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => t('navigation.toggle_menu'), "data-bs-target" => "#navbarNav", "data-bs-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarNav.collapse.navbar-collapse
          %ul.navbar-nav.me-auto
            %li.nav-item
              = link_to t('navigation.home'), root_path, class: "nav-link"
            %li.nav-item.dropdown
              %a.nav-link.dropdown-toggle#categoriesDropdown{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
                = t('navigation.categories')
              %ul.dropdown-menu{"aria-labelledby" => "categoriesDropdown"}
                - Category.all.each do |category|
                  %li
                    = link_to category.name, category_path(category), class: "dropdown-item"
          .d-flex.align-items-center
            .nav-item.dropdown.me-3
              %button.btn.btn-outline-secondary.dropdown-toggle#languageDropdown{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :type => "button"}
                = current_locale_name
              %ul.dropdown-menu.dropdown-menu-end{"aria-labelledby" => "languageDropdown"}
                %li
                  = link_to "Español", url_for(locale: :es), class: "dropdown-item"
                %li
                  = link_to "English", url_for(locale: :en), class: "dropdown-item"
            - if user_signed_in?
              = link_to cart_path, class: "btn btn-outline-primary me-2" do
                %i.bi.bi-cart
                = t('navigation.cart')
                - if current_cart.cart_items.count > 0
                  %span.badge.bg-primary= current_cart.cart_items.count
              .dropdown
                %button.btn.btn-outline-secondary.dropdown-toggle#userDropdown{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :type => "button"}
                  %i.bi.bi-person
                  = current_user.name
                %ul.dropdown-menu.dropdown-menu-end{"aria-labelledby" => "userDropdown"}
                  %li
                    = link_to t('navigation.my_orders'), orders_path, class: "dropdown-item"
                  %li
                    = link_to t('navigation.profile'), edit_user_registration_path, class: "dropdown-item"
                  %li
                    %hr.dropdown-divider
                  %li
                    = button_to t('navigation.sign_out'), destroy_user_session_path, method: :delete, class: "dropdown-item"
            - else
              = link_to t('navigation.sign_in'), new_user_session_path, class: "btn btn-outline-primary me-2"
              = link_to t('navigation.sign_up'), new_user_registration_path, class: "btn btn-primary"

    - if notice
      .alert.alert-success.alert-dismissible.fade.show{role: "alert"}
        = notice
        %button.btn-close{"aria-label" => t('common.close'), "data-bs-dismiss" => "alert", :type => "button"}
    - if alert
      .alert.alert-danger.alert-dismissible.fade.show{role: "alert"}
        = alert
        %button.btn-close{"aria-label" => t('common.close'), "data-bs-dismiss" => "alert", :type => "button"}

    = yield

    %footer.bg-light.mt-5
      .container.py-4
        .row
          .col-md-4.mb-3
            %h5= t('footer.about_us.title')
            %p= t('footer.about_us.description')
          .col-md-4.mb-3
            %h5= t('footer.quick_links.title')
            %ul.list-unstyled
              %li= link_to t('footer.quick_links.home'), root_path, class: "text-decoration-none"
              %li= link_to t('footer.quick_links.products'), products_path, class: "text-decoration-none"
              %li= link_to t('footer.quick_links.categories'), "#", class: "text-decoration-none"
          .col-md-4.mb-3
            %h5= t('footer.contact.title')
            %p
              = t('footer.contact.email')
              %br
              = t('footer.contact.phone')
        %hr
        .text-center
          %p.mb-0= t('footer.copyright', year: Time.current.year)